# Autogenerated wrapper script for SCS_MKL_jll for x86_64-linux-gnu
export libscsmkl

using MKL_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("SCS_MKL")
JLLWrappers.@declare_library_product(libscsmkl, "libscsmkl.so")
function __init__()
    JLLWrappers.@generate_init_header(MKL_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libscsmkl,
        "lib/libscsmkl.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
